# Generated by Django 6.0.7 on 2026-08-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('sent', 'sent'), ('failed', 'failed')], default='pending', max_length=20),
        ),
    ]
