# Generated by Django 6.0.7 on 2026-08-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_remove_channel_config_emailconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'channel', 'verbose_name_plural': 'channels'},
        ),
        migrations.AlterField(
            model_name='emailconfiguration',
            name='password',
            field=models.TextField(),
        ),
    ]
